version: '3'

volumes:
  go_api_postgres_data: {}
  go_api_redis_data:
    driver: local

networks:
  go_api_network:
    driver: bridge

services:
  go_api_postgres:
    container_name: go_api_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=goApiPostgres1234
      - POSTGRES_DB=go_api_db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5435:5432'
    networks:
      - go_api_network
    volumes:
      - ./Assets/docker/go_api_postgres_data:/var/lib/postgresql/data
  go_api_redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    container_name: go_api_redis
    command: redis-server --save 20 1 --loglevel warning --requirepass fuaGUCIVUI678597yHUIHbiivu97668
    volumes:
      - go_api_redis_data:/data
