### Get all categories
GET http://localhost:3000/api/v1/categories
X-API-Key: RAHASIA1234
Accept: application/json

### Create new category
POST http://localhost:3000/api/v1/categories
X-API-Key: RAHASIA1234
Accept: application/json
Content-Type: application/json

{
  "namesss" : "Food 2"
}

### Get category by Id
GET http://localhost:3000/api/v1/categories/0
X-API-Key: RAHASIA1234
Accept: application/json

### Update category by id
PUT http://localhost:3000/api/categories/0
X-API-Key: RAHASIA1234
Accept: application/json
Content-Type: application/json

{
  "name" : "Fashion"
}

### Delete category by id
DELETE http://localhost:3000/api/categories/0
X-API-Key: RAHASIA1234
Accept: application/json
